# Stage 1 Builder
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/Shared.Contracts/ Shared.Contracts/
COPY src/Shared.GameLogic/ Shared.GameLogic /
COPY src/Shared.Security/ Shared.Security/
COPY src/GameServer/KitchenOrchestrator.GameServer.csproj GameServer/
RUN dotnet restore GameServer/KitchenOrchestrator.GameServer.csproj
COPY src/GameServer/ GameServer/
RUN dotnet publish GameServer/KitchenOrchestrator.GameServer.csproj -c Release -o /app/publish

# Stage 2 Runner
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "KitchenOrchestrator.GameServer.dll"]