// <auto-generated />
using System;
using KitchenOrchestrator.IdentityAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KitchenOrchestrator.IdentityAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KitchenOrchestrator.Shared.Contracts.Models.MatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CompletedOrders")
                        .HasColumnType("integer");

                    b.Property<int>("FailedOrders")
                        .HasColumnType("integer");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<string>("FinalState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LevelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("MatchBeginUtc")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime>("MatchEndUtc")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("MatchSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("PerfectOrders")
                        .HasColumnType("integer");

                    b.Property<int>("TargetScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchSessionId")
                        .IsUnique();

                    b.ToTable("MatchHistories");
                });

            modelBuilder.Entity("KitchenOrchestrator.Shared.Contracts.Models.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("IndividualScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchHistoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrdersDelivered")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchHistoryId");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("MatchParticipants");
                });

            modelBuilder.Entity("KitchenOrchestrator.Shared.Contracts.Models.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AccountCreatedUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastLoggedInUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesWon")
                        .HasColumnType("integer");

                    b.Property<int>("PerfectOrders")
                        .HasColumnType("integer");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("KitchenOrchestrator.Shared.Contracts.Models.MatchParticipant", b =>
                {
                    b.HasOne("KitchenOrchestrator.Shared.Contracts.Models.MatchHistory", "MatchHistory")
                        .WithMany("Participants")
                        .HasForeignKey("MatchHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenOrchestrator.Shared.Contracts.Models.PlayerProfile", "PlayerProfile")
                        .WithMany()
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchHistory");

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("KitchenOrchestrator.Shared.Contracts.Models.MatchHistory", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
